name: Update GitHub Profile Card

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        run: |
          echo "Fetching data..."

          # Fetch contributions in 2025
          CONTRIBUTIONS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X POST -d '{"query": "{
              user(login: \"Ishrak-Adit07\") {
                contributionsCollection(from: \"2025-01-01T00:00:00Z\", to: \"2025-12-31T23:59:59Z\") {
                  contributionCalendar { totalContributions }
                }
              }
            }"}' https://api.github.com/graphql | jq '.data.user.contributionsCollection.contributionCalendar.totalContributions')

          # Fetch public repository count
          PUBLIC_REPOS=$(curl -s https://api.github.com/users/Ishrak-Adit07 | jq '.public_repos')

          # Fetch account creation date
          JOIN_DATE=$(curl -s https://api.github.com/users/Ishrak-Adit07 | jq -r '.created_at')
          YEARS_AGO=$(echo $(( $(date +%Y) - $(echo $JOIN_DATE | cut -d'-' -f1) )))

          # Replace placeholders in SVG template
          sed -i "s/{{CONTRIBUTIONS}}/$CONTRIBUTIONS/g" profile-card.svg
          sed -i "s/{{PUBLIC_REPOS}}/$PUBLIC_REPOS/g" profile-card.svg
          sed -i "s/{{YEARS_AGO}}/$YEARS_AGO/g" profile-card.svg

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add profile-card.svg
          git commit -m "Updated GitHub Profile Card" || exit 0
          git push
